### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by IanKirwan** [jeremy-shannon/CarND-Behavioral-Cloning-Project#1]
Hi @jeremy-shannon,

I used the starter kit to create the conda env as you havent included the yml files so assumed that's what you have used, then tried to run your model in that env but get the following error:
```
 Traceback (most recent call last):'
  File "drive.py", line 21, in <module>
    tf.python.control_flow_ops = tf
AttributeError: module 'tensorflow' has no attribute 'python'
```

Have you commited your latest code?
Many thanks

**Comment by EyeEyeloving** [comment]
> Hi @jeremy-shannon,
> 
> I used the starter kit to create the conda env as you havent included the yml files so assumed that's what you have used, then tried to run your model in that env but get the following error:
> 
> ```
>  Traceback (most recent call last):'
>   File "drive.py", line 21, in <module>
>     tf.python.control_flow_ops = tf
> AttributeError: module 'tensorflow' has no attribute 'python'
> ```
> 
> Have you commited your latest code?
> Many thanks

Hi @jeremy-shannon 

I'm so sorry to tell you that I have the same problem when I input `python drive.py model.h5`.

**Comment by jeremy-shannon** [comment]
This code is not maintained and should be assumed woefully obsolete.
